#
# Makefile
JCC = javac

JFLAGS = -g


default: Problem8.class

Problem8.class: Problem8.java
	$(JCC) $(JFLAGS) Problem8.java

# To start over from scratch, type 'make clean'.  
# Removes all .class files, so that the next make rebuilds them
#
clean: 
	$(RM) *.class